# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(603, 456)
        Dialog.setMinimumSize(QtCore.QSize(603, 456))
        Dialog.setMaximumSize(QtCore.QSize(604, 456))
        self.buttonSelectFile = QtWidgets.QPushButton(Dialog)
        self.buttonSelectFile.setGeometry(QtCore.QRect(450, 150, 121, 41))
        self.buttonSelectFile.setObjectName("buttonSelectFile")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 390, 391, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 260, 391, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.buttonOutputPath = QtWidgets.QPushButton(Dialog)
        self.buttonOutputPath.setGeometry(QtCore.QRect(450, 260, 121, 41))
        self.buttonOutputPath.setObjectName("buttonOutputPath")
        self.buttonStart = QtWidgets.QPushButton(Dialog)
        self.buttonStart.setGeometry(QtCore.QRect(450, 390, 121, 41))
        self.buttonStart.setObjectName("buttonStart")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 391, 191))
        self.listWidget.setObjectName("listWidget")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(20, 330, 161, 31))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buttonSelectFile.setText(_translate("Dialog", "选择文件"))
        self.buttonOutputPath.setText(_translate("Dialog", "输出路径"))
        self.buttonStart.setText(_translate("Dialog", "开始"))
        self.checkBox.setText(_translate("Dialog", "输出到原路径"))
